# track, tier(1=core,2=strong,3=worth-a-look), note
NOTES = {
# ---------- MISSION ----------
"IND397":("mission",1,"The single most useful hour if you ship into Government Regions. Real ATO strategies, service parity gaps, and deployment patterns for Bedrock agents across classification levels."),
"IND396":("mission",1,"IRS replaced a sub-10%-accuracy rules engine with an agentic system on GovCloud and went from 10+ weeks to one day. Architecture plus the compliance journey, told by the agency."),
"IND395":("mission",1,"Neurosymbolic AI replacing Drools eligibility engines for SNAP/Medicaid — LLM ingests policy, formal logic verifies it, decisions stay deterministic and auditable. This is the honest answer to 'we can't ship a hallucinating model.'"),
"IND418":("mission",1,"Agentic orchestration inside high-side environments under IL4/IL5 and zero trust. Rare to get this level of detail on the constrained side of the fence."),
"IND409":("mission",1,"NIST 800-171 / CMMC L2 landing zone deep dive, including what they got wrong and iterated on. Open-source CloudFormation on GitHub — a reusable asset, not just a talk."),
"IND398":("mission",2,"Air Force SOC + AWS built a multi-agent Bedrock system for log analysis and one-click containment across DoD accounts. Fifteen minutes, high signal."),
"IND361":("mission",2,"Hands-on CDK build of an edge-to-cloud tokenization data plane: sensitive data stays local, masked payloads go to Bedrock. The workaround pattern for data-localization mandates."),
"IND410":("mission",2,"Kiro in a regulated federal context — steering rules to constrain agent behavior, hooks for automated testing and docs. Practical if compliance is what slows your team down."),
"IND3316":("mission",2,"California Community Colleges cut attempted financial-aid fraud 64% with SageMaker. A genuine public-sector ML case study with numbers, not a genAI demo."),
"HMC314":("mission",2,"Compares Dedicated Local Zones, Outposts, and Regions against data residency, key management, and network separation — plus detecting non-permitted data flows. The sovereignty decision matrix."),
"NET327":("mission",3,"Cross-partition connectivity between commercial, GovCloud, and Sovereign Cloud: VPN, Direct Connect, DNS, and compliance-boundary enforcement. Niche, but nobody else covers it."),
"IND393":("mission",3,"Georgia DCS contact center modernization on Amazon Connect. Useful mostly for the stakeholder-alignment and use-case-prioritization lessons."),
"IND309":("mission",3,"Strategic framing on AI/HPC for defense and national security. Low technical density — go if you need material for leadership conversations."),

# ---------- TRAIN ----------
"AIM347":("train",1,"The best pure-craft session in the catalog for your role: profile kernels, tune collectives, read EFA and Lustre counters, build the dashboards yourself, and leave with a goodput methodology. Full-day-caliber depth."),
"AIM344":("train",1,"Diagnosing GPU cluster failures that single-node debugging never teaches — NCCL timeouts that are really storage, DataLoader forks hanging collectives, GPUs that pass health checks and corrupt results. You leave with a failure-signature runbook."),
"AIM362":("train",1,"A live decision framework for SFT vs DPO vs RLAIF vs RLVR vs multi-turn RL, mapped onto SageMaker Serverless, Training Jobs, HyperPod, and Bedrock Custom Model Import. Bring a real use case; they place it on the map."),
"AIM334":("train",2,"Distributed training on Trainium through native PyTorch and TorchTitan — cluster setup, parallelism strategies, tuning. The cleanest hands-on route into Trainium if you have never touched Neuron."),
"AIM311":("train",2,"Full-stack LLM serving on Trainium: vLLM Neuron, disaggregated inference, prefix-cache-aware routing, then EKS topology-aware scheduling and fault recovery underneath."),
"AIM345":("train",2,"You run both unified and disaggregated inference architectures yourself, move KV cache over EFA, and benchmark against agentic traffic. Leaves you with a real decision framework and runnable configs."),
"AIM312":("train",2,"RLHF and GRPO on Trainium via Neuron, TorchTitan, TRL, and vLLM, with a co-located vs disaggregated RL architecture comparison."),
"AIM325":("train",2,"Managed multi-turn RL on SageMaker that wraps a Strands, LangChain, or CrewAI agent in under 10 lines — reward design, rollouts in managed gym environments, decoupled training compute."),
"AIM435":("train",2,"On-policy distillation on HyperPod EKS: compress a large teacher into a domain-specialized student using the student's own rollouts. Cheaper and more stable than RLVR, and no verifier needed."),
"AIM318":("train",2,"Vision-language model training that survives node crashes and corrupt checkpoints. You simulate failures and recover. Directly relevant if you touch multimodal or geospatial models."),
"AIM326":("train",3,"Workshop on frontier-model inference economics on Trainium with the Neuron stack and open-source frameworks. Overlaps AIM311 — pick one."),
"AIM403":("train",2,"End-to-end data prep, distributed training, and serving on HyperPod, including simulating a node failure and watching training auto-resume. Tiered checkpointing and managed KV cache."),
"AIM406":("train",3,"The Kubernetes-flavored version of AIM403: HyperPod on EKS with checkpointless recovery, then inference on the same cluster. Choose based on whether your platform is EKS."),
"AIM433":("train",2,"HyperPod as one shared GPU pool across data prep, training, post-training, and inference, with team isolation and submission strategies. The multi-team utilization problem, which is a real one in an agency."),
"AIM310":("train",3,"Trainium3 microarchitecture: NeuronCore changes, hardware quantization, softmax acceleration, MoE optimizations, and UltraServer scaling to 144 chips. Go if you evaluate silicon."),
"AIM392":("train",3,"Where EC2 G7e/G7 beats the P-family for prefill, FP4 decode, and pipeline-parallel training, with a TCO comparison. Practical cost-control material."),
"CON414":("train",3,"Model customization and serving on EKS at high GPU utilization, including hybrid nodes spanning cloud and on-premises GPUs."),
"INV517":("train",1,"Distinguished-level: head-of-line blocking on prefill, decode stragglers, pipeline bubbles, temporally-disaggregated pipeline parallelism, constrained decoding with context-sensitive grammars, KV-cache parallelism for multi-million contexts."),
"INV509":("train",2,"Why NUMA topology silently costs you inference throughput across Graviton, Intel, and AMD — thread-to-data alignment, SIMD/AMX bandwidth pressure, host-side effects on KV cache offload."),
"INV511":("train",2,"The design of NKI, the Python-embedded DSL for Trainium's memory hierarchy and compute engines, dissecting production FlashAttention and MoE-routing kernels. Go if you want to write kernels, not just call them."),

# ---------- MLOPS ----------
"AIM408":("mlops",1,"The full governed path: managed MLflow, SageMaker Pipelines with lineage, Model Registry with model cards and approval gates, CI/CD promotion, drift monitoring. Approval gates and lineage are exactly what an ATO package asks for."),
"AIM342":("mlops",1,"Reference architecture for a multi-account, environment-isolated ML platform with registry-driven promotion and human-in-the-loop sign-off, extended to LLM adapter versioning. Built for regulated industries."),
"AIM443":("mlops",2,"One HyperPod training pipeline that deploys the same model into Bedrock or AgentCore, with governance following the model rather than bolted on afterward."),
"AIM456":("mlops",2,"A fine-tuning pipeline that proves its own results: baseline eval, QLoRA fine-tune, RLAIF/RLVR pass, re-eval against the same bar. The discipline most fine-tuning work skips."),
"AIM434":("mlops",2,"Dataset prep as a first-class stage — profiling, auto-labeling, human review of edge cases, dedup, toxicity filtering, synthetic data for coverage gaps, then formatting for SFT, DPO, RLVR, and RLAIF."),
"AIM402":("mlops",3,"Serverless model customization APIs across SFT, DPO, RLVR, RLAIF, and multi-turn RL with no GPUs to manage. The low-friction path when procurement is the bottleneck."),
"ANT302":("mlops",3,"Platform-level what's-new across SageMaker: lakehouse, catalog, governance, dev experience. Efficient way to catch launches without sitting through a keynote."),
"TNC312":("mlops",3,"Hands-on lab: fine-tune for valid tool-call output and consistent persona, then ground it with Bedrock RAG. Good if you want the fine-tune-vs-RAG tradeoff in your hands."),

# ---------- PHYSICAL ----------
"AIM449":("physical",1,"Strands Robots SDK: one Robot() call gives an agent hands, MuJoCo by default and real hardware with a parameter change. Covers perception, VLA policies (GR00T, Cosmos 3, LeRobot), edge-to-cloud split, fleet mesh, and sim-to-real."),
"IND401":("physical",1,"Build a digital twin of a multi-robot manufacturing cell in 60 minutes — virtual PLCs, real fieldbus, Omniverse physics, EC2 backing it. You leave with a validated robotic program and a reusable blueprint."),
"AIM413":("physical",1,"The synthetic-data flywheel for robotics and AV: generate rare edge cases, post-train policies, evaluate, repeat, on HyperPod with EKS and heterogeneous GPU pools. This is the robotics-plus-ML-infra intersection you care about."),
"INV527":("physical",1,"Distinguished-level failure analysis of a trajectory-conditioned lidar world model for a hospital robot fleet: why standard losses fail for generative spatial prediction, why rotation breaks factored attention. A diagnostic framework, not a product pitch."),
"CMP407":("physical",1,"Whiteboards the whole physical-AI pipeline and compares EKS vs Batch vs ParallelCluster across simulation, training, evaluation, and edge deployment, with Capacity Blocks and Spot for cost. They solve attendee architectures live — bring yours."),
"CON409":("physical",2,"AWS Batch orchestrating burst simulation and GPU training end to end, with outputs flowing through a shared data lake back into training. Solves the no-standing-fleet budget problem."),
"CMP408":("physical",2,"DCV streaming an Omniverse and Isaac Sim workstation from EC2 G instances to a browser, with AWS Batch running the same scenes headless across GPU fleets. Fixes the 'engineers lack RTX hardware' problem directly."),
"AIM360":("physical",2,"Panel on world models across video, vision, language, and action for physical AI and autonomous systems, with researchers and customers on production deployments."),
"AIM401":("physical",2,"A Strands agent running the entire RL loop autonomously: generates reward functions from a natural-language objective, evaluates in simulation, diagnoses failures, tunes hyperparameters, iterates to convergence."),
"AIM305":("physical",2,"Fine-tune a transformer world model and deploy robotic agents for real-time inference on Trainium, with parameter-efficient training strategies."),
"AIM458-S":("physical",2,"Full NVIDIA-plus-AWS physical AI pipeline in one workshop: Isaac Sim synthetic data, GR00T and Cosmos training, Omniverse twin, Greengrass edge deploy, AgentCore fleet orchestration. Sponsored, but the toolchain coverage is unmatched."),
"IND352":("physical",2,"Commanding autonomous drone fleets for search-and-rescue with Bedrock Agents, Greengrass, and SageMaker, escalating to humans on confidence thresholds. Human-machine teaming with a public-safety mission."),
"AIM304":("physical",3,"Deploying a real-time video world model on Trainium using Neuron agentic skills that automate compilation, profiling, and kernel selection."),
"AIM323":("physical",3,"World model serving with torch.compile graph fusion and NKI custom kernels for attention. Pairs naturally with INV511."),
"SNR319":("physical",3,"Amazon coordinates a million-plus robots with one model and still keeps humans in the loop, because a wrong action cannot be rolled back. Leadership framing you can reuse verbatim in a mission-risk conversation."),

# ---------- HPC ----------
"CMP406":("hpc",1,"Hands-on build of production clusters with AWS Parallel Computing Service — job submission, resource optimization, the managed replacement for hand-rolled ParallelCluster."),
"CMP357":("hpc",1,"A decision framework for choosing compute across HPC and AI at scale by price and timing. The session that saves you the most money per minute spent in it."),
"CMP308":("hpc",2,"Migrating existing HPC estates onto PCS at scale. Relevant if you inherit an on-prem cluster, which in public sector you usually do."),
"CMP410":("hpc",2,"Using AI to tune HPC configurations on AWS rather than hand-tuning them."),
"CMP404":("hpc",3,"Genomics HPC pipeline workshop. Take it as a template for any scientific batch pipeline, not just bioinformatics."),
"CMP338":("hpc",3,"Crash prediction models combining HPC and AI — a concrete simulation-plus-ML pattern."),
"NET328":("hpc",2,"How Elastic Fabric Adapter carries the largest AI workloads on AWS. The networking half of why your multi-node training run is slow."),
"STG354":("hpc",3,"Storage throughput and IOPS tuning for HPC. Pairs with AIM347's Lustre material."),

# ---------- DATA ----------
"ANT311":("data",1,"Agents fire hundreds of sub-queries per task and cascade retrieval failures into hallucinations. What breaks in traditional search at agent scale and how OpenSearch addresses it."),
"ANT336":("data",1,"Building data products good enough for agents to consume. The upstream work that determines whether any of your downstream agent work succeeds."),
"ANT303":("data",2,"Open lakehouse on Apache Iceberg for analytics and AI. The format decision that keeps your data portable across engines and, importantly, across partitions."),
"ANT330":("data",2,"Agentic data engineering inside SageMaker — agents building and maintaining pipelines rather than you writing every ETL job."),
"ANT316":("data",2,"From prompt to pipeline: the chalk-talk version of agentic data engineering, with more room to argue about where it breaks."),
"ANT407":("data",2,"Governing agents with data quality, lineage, and business context. Lineage is the artifact auditors actually ask you for."),
"ANT423":("data",3,"Building a managed context layer from semantic data with AWS Context. New primitive worth understanding early."),
"ANT318":("data",3,"Making vector search faster, more relevant, and cheaper. Practical tuning for any RAG system you already run."),
"ANT322":("data",3,"Agent retrieval specifically on OpenSearch Service. Narrower than ANT311; skip if you take that one."),
"IND366":("data",2,"Zero-shot forecasting with Chronos 2 in SageMaker Unified Studio — no historical training, no cold-start problem. Framed for retail, but the pattern transfers to caseload, demand, and staffing forecasts."),
"STG306":("data",3,"Iceberg data lakes on S3 Tables. The managed-table-maintenance question, answered."),
"STG343":("data",2,"Storage architecture as an AI performance lever rather than an afterthought. Complements AIM347."),

# ---------- BUILD ----------
"DVT415":("build",1,"Reusable skills that encode team know-how, custom agents for specific jobs, and steering files that carry conventions across sessions. Demoed in Kiro but the principles transfer to any agentic coding tool."),
"DVT339":("build",1,"What power users actually do to keep multi-agent orchestration from going brittle as context fills and the agent loses its plan. Bring your own edge cases."),
"ARC408":("build",2,"Specs, not vibes: strangling a monolith from inside the IDE. The disciplined counterweight to vibe-coding, which matters more when your code needs to pass review."),
"DVT405":("build",2,"How Kiro validates specs before writing any code. Directly relevant to shipping under a compliance regime where intent has to be documented anyway."),
"DVT320":("build",3,"How Kiro improves across sessions. Interesting for how they built the learning loop, not just for using the tool."),
"DVT332":("build",3,"Kiro Crew internals: orchestration, memory, and safe autonomy. Architecture-level view of a multi-agent coding system."),
"AIM416":("build",2,"Running coding agents at scale on AgentCore — the infrastructure question once agents stop being one developer's laptop experiment."),
"AIM307":("build",3,"Turning a coding agent into an always-on dev team with AgentCore."),
"AIM372":("build",3,"Anthropic models on AWS: what is available and how to deploy it. Efficient orientation if Claude is in your stack."),
"SVS303":("build",3,"AI-driven serverless development with Kiro. Take it if serverless is your default application shape."),
"TNC336":("build",3,"Bootcamp on the AI-Driven Development Lifecycle. Longer format — only worth it if you are trying to change how a whole team works."),

# ---------- RIGOR ----------
"AIM351":("rigor",1,"Build a working continuous evaluation pipeline: evaluation datasets, LLM-as-judge plus programmatic scoring, performance tracking over time, alerts on quality regressions. You leave with something you can adapt Monday."),
"INV506":("rigor",1,"Provable safety envelopes for probabilistic agents, drawn from the formal verification research behind AgentCore policy — automated reasoning for policy correctness, action-space reduction before execution. This is how you get an agent past a security review."),
"INV526":("rigor",1,"What neurosymbolic AI can actually prove about agent behavior: autoformalization into temporal logic, SAT solvers, LLM-guided proof search in Lean, and an honest map of what remains undecidable."),
"INV503":("rigor",2,"Evaluating AI safety with formal guarantees rather than benchmark scores. Pairs with INV506 and INV526 as a coherent three-session arc."),
"INV508":("rigor",2,"How neurosymbolic AI formalizes natural language into verifiable logic — the mechanism underneath IND395's eligibility-engine work."),
"INV522":("rigor",2,"The evaluator is the algorithm: evolving state of the art for $15. A sharp argument about where progress actually comes from."),
"INV514":("rigor",3,"Measuring emergent risks in frontier models. Research-flavored, useful if you advise on model selection policy."),
"AIM314":("rigor",2,"Governance for agents making high-stakes decisions — a workshop, so you build the controls rather than hear about them."),
"BIZ330":("rigor",3,"A production-readiness framework for agents: evaluate, disclose, safeguard. Useful checklist material for a review board."),
"AIM278-S":("rigor",3,"Open-source agent observability and evals with AgentCore and Langfuse. Sponsored, but Langfuse is a real option if you want to avoid lock-in."),
}
